Fix an runtime error cannot load such file -- csv
```
❯ bundle exec rake create_zip_code_data
/Users/yudai.takada/ydah/jp_prefecture/Rakefile:8: warning: csv was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
rake aborted!
LoadError: cannot load such file -- csv (LoadError)
/Users/yudai.takada/ydah/jp_prefecture/Rakefile:8:in 'block in <top (required)>'
/Users/yudai.takada/.rbenv/versions/3.5-dev/bin/bundle:25:in 'Kernel#load'
/Users/yudai.takada/.rbenv/versions/3.5-dev/bin/bundle:25:in '<main>'
Tasks: TOP => create_zip_code_data
(See full trace by running task with --trace)
```